name: Build Cheat Engine

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - name: Get Lazarus info
        shell: bash
        id: get-info
        run: |
          echo "lazarus=$(node ./.github/workflows/scripts/getLazarusVersion.js)" >> $GITHUB_OUTPUT
          echo "fpc=$(node ./.github/workflows/scripts/getFpcVersion.js)" >> $GITHUB_OUTPUT
          echo "dependencies=$(node ./.github/workflows/scripts/getPackages.js)" >> $GITHUB_OUTPUT
      - name: Make working dir
        shell: cmd
        run: mkdir ${{ github.workspace }}\work
      - name: Install Lazarus
        shell: bash
        run: node ./.github/workflows/scripts/install.js
        env:
          LAZARUS_VERSION: ${{ steps.get-info.outputs.lazarus }}
          FPC_VERSION: ${{ steps.get-info.outputs.fpc }}
      - name: Install 32bit compat
        shell: bash
        run: node ./.github/workflows/scripts/install32bitCompat.js
        env:
          LAZARUS_VERSION: ${{ steps.get-info.outputs.lazarus }}
          FPC_VERSION: ${{ steps.get-info.outputs.fpc }}
      - name: Add Lazarus to path
        shell: bash
        run: |
          echo "${{github.workspace}}\work\lazarus" >> $GITHUB_PATH
          echo "${{github.workspace}}\work\lazarus\fpc\${{ steps.get-info.outputs.fpc }}" >> $GITHUB_PATH
      - name: Apply fixes
        shell: bash
        run: py ./.github/workflows/scripts/fixes.py
      # todo: setup cache
      - name: Build 32-Bit
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 32-bit" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Build 64-Bit
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 64-bit" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Build 64-Bit O4 AVX2
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 64-bit O4 AVX2" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Zip artifact
        if: always()
        shell: cmd
        run: 7z a -tzip release.zip * -r
        working-directory: "./Cheat Engine/bin"
      - name: Release artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: "Cheat Engine/bin/release.zip"
