name: Build Cheat Engine

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - name: Get Lazarus dependencies
        shell: bash
        id: get-info
        run: |
          echo "::set-output name=lazarus::$(node ./.github/workflows/scripts/getLazarusVersion.js)"
          echo "::set-output name=fpc::$(node ./.github/workflows/scripts/getFpcVersion.js)"
          echo "::set-output name=dependencies::$(node ./.github/workflows/scripts/getPackages.js)"
      # todo: setup cache
      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3.2
        with:
          lazarus-version: ${{ steps.get-info.outputs.lazarus }}
          include-packages: ${{ steps.get-info.outputs.dependencies }}
          with-cache: false
      - name: Install 32bit compat
        shell: bash
        run: node ./.github/workflows/scripts/install32bitCompat.js
        env:
          LAZARUS_VERSION: ${{ steps.get-info.outputs.lazarus }}
          FPC_VERSION: ${{ steps.get-info.outputs.fpc }}
      - name: Build 32-Bit
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 32-bit" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Build 64-Bit
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 64-bit" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Build 64-Bit O4 AVX2
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 64-bit O4 AVX2" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Zip artifact
        if: always()
        shell: cmd
        run: 7z a -tzip release.zip * -r
        working-directory: "./Cheat Engine/bin"
      - name: Release artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: "Cheat Engine/bin/release.zip"
