name: "Upstream Sync"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.sync.outputs.has_new_commits }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: cheat-engine/cheat-engine
  start_build:
    needs: sync_latest_from_upstream
    if: needs.sync_latest_from_upstream.outputs.has_new_commits == 'true'
    uses: ./.github/workflows/buildCE.yml
